# Basic linear algebra in Julia
Based on work by Andreas Noack Jensen (MIT) (https://github.com/andreasnoack)


First let's define a random matrix

In [15]:
A = rand(1:4, 3, 3)

3×3 Matrix{Int64}:
 1  4  2
 2  3  2
 4  1  1

Define a vector of ones

In [24]:
x = ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

Many of the basic operations are the same as in other languages

In [25]:
b = A * x

3-element Vector{Float64}:
 7.0
 7.0
 6.0


#### Transposition

In [19]:
A'

3×3 adjoint(::Matrix{Int64}) with eltype Int64:
 1  2  4
 4  3  1
 2  2  1

and we can get the transpose with

In [20]:
transpose(A)

3×3 transpose(::Matrix{Int64}) with eltype Int64:
 1  2  4
 4  3  1
 2  2  1

#### Transposed multiplication
Julia allows us to write this without *

In [21]:
A'A

3×3 Matrix{Int64}:
 21  14  10
 14  26  15
 10  15   9

#### Solving linear systems 
The problem $Ax=b$ for ***square*** $A$ is solved by the \ operator.

In [26]:
x = A \ b

3-element Vector{Float64}:
 1.0
 0.9999999999999998
 1.0000000000000004

`A\b` gives us the *least squares solution* if we have an overdetermined linear system (a "tall" matrix)

In [22]:
Atall = rand(3, 2)

3×2 Matrix{Float64}:
 0.423735  0.375893
 0.747144  0.67883
 0.702932  0.285837

In [27]:
Atall \ b

2-element Vector{Float64}:
 6.632888991672504
 4.891429275931603

and the *minimum norm least squares solution* if we have a rank-deficient least squares problem

In [28]:
v = rand(3)
rankdef = hcat(v, v)

3×2 Matrix{Float64}:
 0.0246885  0.0246885
 0.37501    0.37501
 0.0918014  0.0918014

In [29]:
rankdef \ b

2-element Vector{Float64}:
 11.18696227587687
 11.186962275876876

Julia also gives us the minimum norm solution when we have an underdetermined solution (a "short" matrix)

In [30]:
bshort = rand(2)
Ashort = rand(2, 3)

2×3 Matrix{Float64}:
 0.262339  0.715286  0.71453
 0.600741  0.307078  0.0221058

In [31]:
Ashort \ bshort

3-element Vector{Float64}:
  0.3530108738618392
  0.04307411807582378
 -0.15361897630145296

# The LinearAlgebra library

While much of linear algebra is available in Julia by default (as shown above), there's a standard library named `LinearAlgebra` that brings in many more relevant names and functions. In particular, it provides factorizations and some structured matrix types.  As with all packages, you can bring these additional features into your session with a `using LinearAlgebra`.

### Exercises

#### 10.1 
Take the inner product (or "dot" product) of a vector `v` with itself and assign it to variable `dot_v`. 



In [4]:
v = [1, 2, 3]
v' * v

14

In [13]:
using LinearAlgebra
dot(v, v)

14

In [6]:
⋅ #\cdot + <<tab>>
dot_v = ⋅(v, v)

14

In [7]:
@assert dot_v == 14

#### 10.2 
Take the outer product of a vector v with itself and assign it to variable `outer_v`

In [32]:
v = [1, 2, 3]
outer_v = v * v'

3×3 Matrix{Int64}:
 1  2  3
 2  4  6
 3  6  9

In [33]:
@assert outer_v == [1 2 3
                    2 4 6
                    3 6 9]

#### 10.3 
Take the cross product of a vector v with itself and assign it to variable `cross_v`

In [36]:
cross_v = cross(v, v)

3-element Vector{Int64}:
 0
 0
 0

In [37]:
@assert cross_v == [0, 0, 0]